#!/bin/bash

    res=`curl -Is --head --connect-timeout 5 'http://nspj.bydgoszcz.pl'| head -n 1 | grep -c 'HTTP/1.1 200 OK'`
    if [ $res -ne 1 ]
    then
        echo "restart: `date` \n" >> /home/michal/django/nspj_parafia/dziennik_restartow.txt
        if [ -f /tmp/nspj_parafia.pid ]; then 
            kill `cat /tmp/nspj_parafia.pid`
        fi
        cd /home/michal/django/nspj_parafia
        source bin/activate
        gunicorn nspj_parafia.wsgi -b 127.0.0.1:`cat ./port.txt` -w7 -p /tmp/nspj_parafia.pid -D
    else
        echo 'ok' `date` >> /home/michal/django/nspj_parafia/dziennik_sprawdzen.txt
    fi
  


